### ISSUE TITLE
Problems in make_align_from_blast.sh

### ISSUE THREAD

**Issue by piosierra** [annaprotasio/TE_ManAnnot#1]
Hello Anna,

I have run into a couple of issues with the script make_align_from_blast.sh:

1- mafft correct option as of version v7.505 (2022/Apr/10) is --thread (instead of --threads). This now produces an error that blocks the script. (As a side not, as an optimization, setting it to -1 so let it automatically choose the number of threads, rather than using just one.)

2- The definition of the out variable seems to not work correctly with the rest of the script
out=`echo "$fasta_in" | cut -d'.' -f1`
Changing it to the original one in the make_fasta_from_blast.sh worked for me, but I am not sure that is the correct behaviour.
out=`basename $2`

With those two changes it seems to work fine.

Thanks a lot for the scripts.

**Comment by annaprotasio** [comment]
Thank you @piosierra  for raising these issues. Now fixed!
