### ISSUE TITLE
Problem with generating col4.txt

### ISSUE THREAD

**Issue by rotifergirl** [annaprotasio/TE_ManAnnot#2]
I ran into a bit of a problem with generating col4.txt because not all of the element names were exact matches, due to the trailing "_number" introduced by getorf, and the fact that some elements have a different number of "/" in their name (e.g. rnd-6_family-15607#Unknown or rnd-6_family-16313#DNA/hAT-Ac)

I eneded up finding a (probably inelegant) workaround, by chopping off the "_number" bit of the name earlier in the generation of the pf.domains.count file. Hopefully this is helpful for someone else :)

`awk '{if ($6~/^PF/) {print $1}}' < pfam.results | sed 's/_[0-9]\+//'|sed  's/_/\//2;s/_/ /2'|awk '{print $1}' | sort| sed  's/\/'[0-9]'//'> fixed.pf.domains.count`

**Comment by Yiguan** [comment]
I exactly have the same problem!! In my case , the problem is caused by some 'Unknown' tags and I need to remove the numbers after 'Unknown'. My sulution is:


```bash
awk '{if ($6~/^PF/) {print $1}}' < pfam.results |  sed 's/_/\//2;s/_/ /2' | awk '{print $1}' | sed 's/#Unknown\/[0-9]*/#Unknown/g' | sort > pf.domains.count
```
